name: CI

on:
  push:
    branches:
    - master

jobs:
  clone_job:
    name: clone file to ghpage
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout ðŸ›Žï¸
      run: | 
        git checkout master
        cd ./dist
        echo "eviler.top" > RENAME

    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: dist